import {
  Farmer,
  Plantation,
  Employee,
  Weighing,
  Credit,
  Transporter,
  Vehicle,
  Bank,
  Bulletin,
  CompanySettings,
  CreditInstallment,
} from '@/types';

// Helper to generate dates
const getDate = (daysAgo: number) => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

const getDateOnly = (daysAgo: number) => {
  return getDate(daysAgo).split('T')[0];
};

// Company Settings
export const companySettings: CompanySettings = {
  id: '1',
  name: 'Coopérative Agricole de Bongouanou',
  address: 'Quartier Commerce, BP 123, Bongouanou, Côte d\'Ivoire',
  phone: '+225 27 35 62 45 78',
  email: 'contact@coop-bongouanou.ci',
  registrationNumber: 'CI-BGN-2020-0045',
  customMessage: 'Prime de 10 FCFA/kg après 6 livraisons sur une période de 6 mois',
  bonusEnabled: true,
  bonusMinDeliveries: 6,
  bonusAmountPerKg: 10,
  bonusPeriodMonths: 6,
  createdAt: getDate(365),
  updatedAt: getDate(30),
};

// Banks
export const banks: Bank[] = [
  {
    id: '1',
    name: 'SGBCI',
    agency: 'Bongouanou Centre',
    createdAt: getDate(200),
    updatedAt: getDate(200),
  },
  {
    id: '2',
    name: 'Ecobank',
    agency: 'Bongouanou',
    createdAt: getDate(200),
    updatedAt: getDate(200),
  },
  {
    id: '3',
    name: 'COOPEC',
    agency: 'Bongouanou Billon',
    createdAt: getDate(200),
    updatedAt: getDate(200),
  },
  {
    id: '4',
    name: 'NSIA Banque',
    agency: 'Bongouanou',
    createdAt: getDate(200),
    updatedAt: getDate(200),
  },
];

// Transporters
export const transporters: Transporter[] = [
  {
    id: '1',
    name: 'Transport Kouassi & Frères',
    createdAt: getDate(180),
    updatedAt: getDate(180),
  },
  {
    id: '2',
    name: 'SARL Trans-Cacao',
    createdAt: getDate(180),
    updatedAt: getDate(180),
  },
  {
    id: '3',
    name: 'Yao Transport',
    createdAt: getDate(180),
    updatedAt: getDate(180),
  },
];

// Vehicles
export const vehicles: Vehicle[] = [
  {
    id: '1',
    registration: 'AB-1234-CI',
    type: 'camion',
    transporterId: '1',
    driverName: 'Kouassi Yao',
    createdAt: getDate(180),
    updatedAt: getDate(180),
  },
  {
    id: '2',
    registration: 'CD-5678-CI',
    type: 'camionnette',
    transporterId: '1',
    driverName: 'Koffi Jean',
    createdAt: getDate(180),
    updatedAt: getDate(180),
  },
  {
    id: '3',
    registration: 'EF-9012-CI',
    type: 'tricycle',
    transporterId: '2',
    driverName: 'N\'Guessan Marie',
    createdAt: getDate(180),
    updatedAt: getDate(180),
  },
  {
    id: '4',
    registration: 'GH-3456-CI',
    type: 'camion',
    transporterId: '2',
    driverName: 'Bamba Souleymane',
    createdAt: getDate(180),
    updatedAt: getDate(180),
  },
  {
    id: '5',
    registration: 'IJ-7890-CI',
    type: 'pickup',
    transporterId: '3',
    driverName: 'Yao Pascal',
    createdAt: getDate(180),
    updatedAt: getDate(180),
  },
];

// Farmers (Cocoa farmers / merged from planters)
export const farmers: Farmer[] = [
  {
    id: '1',
    code: 'PLT-001',
    firstName: 'Kouassi',
    lastName: 'Yao',
    village: 'Akpassi',
    plantationSize: 5.5,
    latitude: 6.6517,
    longitude: -4.2011,
    phone: '+225 05 44 33 22 11',
    idCardNumber: 'CI2345678901',
    bankName: 'SGBCI',
    bankAgency: 'Bongouanou Centre',
    bankAccountNumber: 'CI93 5001 1234 5678 9012 3456',
    createdAt: getDate(250),
    updatedAt: getDate(250),
  },
  {
    id: '2',
    code: 'PLT-002',
    firstName: 'Amani',
    lastName: 'Kouamé',
    village: 'Allangba',
    plantationSize: 3.2,
    latitude: 6.6420,
    longitude: -4.1950,
    phone: '+225 07 55 66 77 88',
    idCardNumber: 'CI3456789012',
    bankName: 'Ecobank',
    bankAgency: 'Bongouanou',
    bankAccountNumber: 'CI76 3002 9876 5432 1098 7654',
    createdAt: getDate(250),
    updatedAt: getDate(250),
  },
  {
    id: '3',
    code: 'PLT-003',
    firstName: 'N\'Guessan',
    lastName: 'Koffi',
    village: 'Ehuikro',
    plantationSize: 7.8,
    latitude: 6.6600,
    longitude: -4.2100,
    phone: '+225 01 23 45 67 89',
    idCardNumber: 'CI4567890123',
    bankName: 'COOPEC',
    bankAgency: 'Bongouanou Billon',
    bankAccountNumber: 'CI45 4003 1111 2222 3333 4444',
    createdAt: getDate(250),
    updatedAt: getDate(250),
  },
  {
    id: '4',
    code: 'PLT-004',
    firstName: 'Aya',
    lastName: 'Brou',
    village: 'Andé',
    plantationSize: 4.5,
    latitude: 6.6350,
    longitude: -4.2200,
    phone: '+225 05 98 76 54 32',
    idCardNumber: 'CI5678901234',
    bankName: 'SGBCI',
    bankAgency: 'Bongouanou Centre',
    bankAccountNumber: 'CI93 5001 5555 6666 7777 8888',
    createdAt: getDate(250),
    updatedAt: getDate(250),
  },
  {
    id: '5',
    code: 'PLT-005',
    firstName: 'Konan',
    lastName: 'Jean-Marc',
    village: 'Akpassi',
    plantationSize: 6.2,
    latitude: 6.6500,
    longitude: -4.2050,
    phone: '+225 07 11 22 33 44',
    idCardNumber: 'CI6789012345',
    bankName: 'NSIA Banque',
    bankAgency: 'Bongouanou',
    bankAccountNumber: 'CI88 6004 9999 8888 7777 6666',
    createdAt: getDate(250),
    updatedAt: getDate(250),
  },
];

// Weighings
export const weighings: Weighing[] = [
  // PLT-001 weighings
  {
    id: '1',
    farmerId: '1',
    period: 'PA-11/2024-1',
    weighingDate: getDateOnly(45),
    transporterId: '1',
    vehicleId: '1',
    driverName: 'Kouassi Yao',
    vehicleRegistration: 'AB-1234-CI',
    loadedWeight: 1850,
    emptyWeight: 350,
    netWeight: 1500,
    price: 275,
    transportCost: 52500, // 35 FCFA/kg * 1500
    taxRate: 1.5,
    createdAt: getDate(45),
    updatedAt: getDate(45),
  },
  {
    id: '2',
    farmerId: '1',
    period: 'PA-12/2024-1',
    weighingDate: getDateOnly(15),
    transporterId: '1',
    vehicleId: '2',
    driverName: 'Koffi Jean',
    vehicleRegistration: 'CD-5678-CI',
    loadedWeight: 2200,
    emptyWeight: 400,
    netWeight: 1800,
    price: 275,
    transportCost: 63000,
    taxRate: 1.5,
    createdAt: getDate(15),
    updatedAt: getDate(15),
  },
  // PLT-002 weighings
  {
    id: '3',
    farmerId: '2',
    period: 'PA-11/2024-1',
    weighingDate: getDateOnly(50),
    transporterId: '2',
    vehicleId: '3',
    driverName: 'N\'Guessan Marie',
    vehicleRegistration: 'EF-9012-CI',
    loadedWeight: 950,
    emptyWeight: 150,
    netWeight: 800,
    price: 275,
    transportCost: 28000,
    taxRate: 1.5,
    createdAt: getDate(50),
    updatedAt: getDate(50),
  },
  {
    id: '4',
    farmerId: '2',
    period: 'PA-12/2024-1',
    weighingDate: getDateOnly(20),
    transporterId: '2',
    vehicleId: '4',
    driverName: 'Bamba Souleymane',
    vehicleRegistration: 'GH-3456-CI',
    loadedWeight: 1650,
    emptyWeight: 350,
    netWeight: 1300,
    price: 275,
    transportCost: 45500,
    taxRate: 1.5,
    createdAt: getDate(20),
    updatedAt: getDate(20),
  },
  // PLT-003 weighings
  {
    id: '5',
    farmerId: '3',
    period: 'PA-11/2024-1',
    weighingDate: getDateOnly(40),
    transporterId: '1',
    vehicleId: '1',
    driverName: 'Kouassi Yao',
    vehicleRegistration: 'AB-1234-CI',
    loadedWeight: 2800,
    emptyWeight: 500,
    netWeight: 2300,
    price: 275,
    transportCost: 80500,
    taxRate: 1.5,
    createdAt: getDate(40),
    updatedAt: getDate(40),
  },
  {
    id: '6',
    farmerId: '3',
    period: 'PA-12/2024-1',
    weighingDate: getDateOnly(10),
    transporterId: '3',
    vehicleId: '5',
    driverName: 'Yao Pascal',
    vehicleRegistration: 'IJ-7890-CI',
    loadedWeight: 3100,
    emptyWeight: 450,
    netWeight: 2650,
    price: 275,
    transportCost: 92750,
    taxRate: 1.5,
    createdAt: getDate(10),
    updatedAt: getDate(10),
  },
  // PLT-004 weighings
  {
    id: '7',
    farmerId: '4',
    period: 'PA-11/2024-1',
    weighingDate: getDateOnly(55),
    transporterId: '2',
    vehicleId: '4',
    driverName: 'Bamba Souleymane',
    vehicleRegistration: 'GH-3456-CI',
    loadedWeight: 1400,
    emptyWeight: 300,
    netWeight: 1100,
    price: 275,
    transportCost: 38500,
    taxRate: 1.5,
    createdAt: getDate(55),
    updatedAt: getDate(55),
  },
  // PLT-005 weighings
  {
    id: '8',
    farmerId: '5',
    period: 'PA-11/2024-1',
    weighingDate: getDateOnly(48),
    transporterId: '3',
    vehicleId: '5',
    driverName: 'Yao Pascal',
    vehicleRegistration: 'IJ-7890-CI',
    loadedWeight: 2450,
    emptyWeight: 400,
    netWeight: 2050,
    price: 275,
    transportCost: 71750,
    taxRate: 1.5,
    createdAt: getDate(48),
    updatedAt: getDate(48),
  },
  {
    id: '9',
    farmerId: '5',
    period: 'PA-12/2024-1',
    weighingDate: getDateOnly(12),
    transporterId: '1',
    vehicleId: '2',
    driverName: 'Koffi Jean',
    vehicleRegistration: 'CD-5678-CI',
    loadedWeight: 1950,
    emptyWeight: 350,
    netWeight: 1600,
    price: 275,
    transportCost: 56000,
    taxRate: 1.5,
    createdAt: getDate(12),
    updatedAt: getDate(12),
  },
];

// Credits with installments
export const credits: Credit[] = [
  {
    id: '1',
    farmerId: '1',
    type: 'money',
    amount: 150000,
    description: 'Avance sur salaire pour scolarité',
    date: getDateOnly(90),
    installmentsCount: 6,
    deductionStartDate: getDateOnly(60),
    installments: [
      {
        id: '1-1',
        creditId: '1',
        amount: 25000,
        dueDate: getDateOnly(60),
        isPaid: true,
        paidDate: getDateOnly(60),
      },
      {
        id: '1-2',
        creditId: '1',
        amount: 25000,
        dueDate: getDateOnly(30),
        isPaid: true,
        paidDate: getDateOnly(30),
      },
      {
        id: '1-3',
        creditId: '1',
        amount: 25000,
        dueDate: getDateOnly(0),
        isPaid: false,
      },
      {
        id: '1-4',
        creditId: '1',
        amount: 25000,
        dueDate: getDateOnly(-30),
        isPaid: false,
      },
      {
        id: '1-5',
        creditId: '1',
        amount: 25000,
        dueDate: getDateOnly(-60),
        isPaid: false,
      },
      {
        id: '1-6',
        creditId: '1',
        amount: 25000,
        dueDate: getDateOnly(-90),
        isPaid: false,
      },
    ],
    isPaid: false,
    createdAt: getDate(90),
    updatedAt: getDate(30),
  },
  {
    id: '2',
    farmerId: '2',
    type: 'tools',
    amount: 85000,
    description: 'Achat pulvérisateur et machettes',
    date: getDateOnly(120),
    installmentsCount: 4,
    deductionStartDate: getDateOnly(90),
    installments: [
      {
        id: '2-1',
        creditId: '2',
        amount: 21250,
        dueDate: getDateOnly(90),
        isPaid: true,
        paidDate: getDateOnly(90),
      },
      {
        id: '2-2',
        creditId: '2',
        amount: 21250,
        dueDate: getDateOnly(60),
        isPaid: true,
        paidDate: getDateOnly(60),
      },
      {
        id: '2-3',
        creditId: '2',
        amount: 21250,
        dueDate: getDateOnly(30),
        isPaid: false,
      },
      {
        id: '2-4',
        creditId: '2',
        amount: 21250,
        dueDate: getDateOnly(0),
        isPaid: false,
      },
    ],
    isPaid: false,
    createdAt: getDate(120),
    updatedAt: getDate(60),
  },
  {
    id: '3',
    farmerId: '3',
    type: 'money',
    amount: 200000,
    description: 'Prêt pour frais médicaux',
    date: getDateOnly(60),
    installmentsCount: 8,
    deductionStartDate: getDateOnly(30),
    installments: [
      {
        id: '3-1',
        creditId: '3',
        amount: 25000,
        dueDate: getDateOnly(30),
        isPaid: true,
        paidDate: getDateOnly(30),
      },
      {
        id: '3-2',
        creditId: '3',
        amount: 25000,
        dueDate: getDateOnly(0),
        isPaid: false,
      },
      {
        id: '3-3',
        creditId: '3',
        amount: 25000,
        dueDate: getDateOnly(-30),
        isPaid: false,
      },
      {
        id: '3-4',
        creditId: '3',
        amount: 25000,
        dueDate: getDateOnly(-60),
        isPaid: false,
      },
      {
        id: '3-5',
        creditId: '3',
        amount: 25000,
        dueDate: getDateOnly(-90),
        isPaid: false,
      },
      {
        id: '3-6',
        creditId: '3',
        amount: 25000,
        dueDate: getDateOnly(-120),
        isPaid: false,
      },
      {
        id: '3-7',
        creditId: '3',
        amount: 25000,
        dueDate: getDateOnly(-150),
        isPaid: false,
      },
      {
        id: '3-8',
        creditId: '3',
        amount: 25000,
        dueDate: getDateOnly(-180),
        isPaid: false,
      },
    ],
    isPaid: false,
    createdAt: getDate(60),
    updatedAt: getDate(30),
  },
  {
    id: '4',
    farmerId: '4',
    type: 'tools',
    amount: 120000,
    description: 'Achat équipement protection et outils',
    date: getDateOnly(100),
    isPaid: true,
    paidDate: getDateOnly(10),
    createdAt: getDate(100),
    updatedAt: getDate(10),
  },
];

// Sample Bulletins
export const bulletins: Bulletin[] = [
  {
    id: '1',
    farmerId: '1',
    period: 'PA-11/2024-1',
    weighingIds: ['1'],
    grossAmount: 412500, // 1500kg * 275
    deductions: [
      {
        creditId: '1',
        creditType: 'money',
        description: 'Échéance crédit scolarité (1/6)',
        amount: 25000,
      },
    ],
    totalDeductions: 25000,
    netAmount: 387500,
    status: 'validated',
    generatedDate: getDateOnly(44),
    validatedDate: getDateOnly(43),
    createdAt: getDate(44),
    updatedAt: getDate(43),
  },
  {
    id: '2',
    farmerId: '2',
    period: 'PA-11/2024-1',
    weighingIds: ['3'],
    grossAmount: 220000, // 800kg * 275
    deductions: [
      {
        creditId: '2',
        creditType: 'tools',
        description: 'Échéance crédit outils (1/4)',
        amount: 21250,
      },
    ],
    totalDeductions: 21250,
    netAmount: 198750,
    status: 'validated',
    generatedDate: getDateOnly(49),
    validatedDate: getDateOnly(48),
    createdAt: getDate(49),
    updatedAt: getDate(48),
  },
  {
    id: '3',
    farmerId: '3',
    period: 'PA-11/2024-1',
    weighingIds: ['5'],
    grossAmount: 632500, // 2300kg * 275
    deductions: [
      {
        creditId: '3',
        creditType: 'money',
        description: 'Échéance crédit médical (1/8)',
        amount: 25000,
      },
    ],
    totalDeductions: 25000,
    netAmount: 607500,
    status: 'validated',
    generatedDate: getDateOnly(39),
    validatedDate: getDateOnly(38),
    createdAt: getDate(39),
    updatedAt: getDate(38),
  },
];

export const allFixtures = {
  companySettings,
  banks,
  transporters,
  vehicles,
  farmers,
  weighings,
  credits,
  bulletins,
};
